type: google.api.Service
config_version: 3

http:
  rules:
    - selector: nodamatics.staking.islm.IslamicStaking.GetValidatorInfo
      get: /getValidatorInfo
    - selector: nodamatics.staking.islm.IslamicStaking.GetStakingStats
      get: /getStakingStats
    - selector: nodamatics.staking.islm.IslamicStaking.BuildDelegateTransaction
      post: /buildDelegateTransaction
      body: "*"
    - selector: nodamatics.staking.islm.IslamicStaking.BuildWithdrawRewardTransaction
      post: /buildWithdrawRewardTransaction
      body: "*"
    - selector: nodamatics.staking.islm.IslamicStaking.BuildUndelegateTransaction
      post: /BuildUndelegateTransaction
      body: "*"
    - selector: nodamatics.staking.islm.IslamicStaking.BroadcastTransaction
      post: /BroadcastTransaction
      body: "*"